from selenium import webdriver
from selenium.webdriver.chrome.options import Options
import time
from unstructured.partition.html import partition_html

# CODE GENERATED BY CLAUDE.

def extract_listings_found(html_content:str):
    us_elems = partition_html(text=html_content)
    page_text_chunks = '\n'.join([str(el) for el in us_elems])
    return page_text_chunks

# Initialize the browser (using Chrome as default)

# Set up Chrome options for headless mode
chrome_options = Options()
# chrome_options.add_argument("--headless=new")
chrome_options.add_argument("--no-sandbox")
chrome_options.add_argument("--disable-dev-shm-usage")

CHROME_DRIVER = webdriver.Chrome(options=chrome_options)


def get_properties_for_user(neighbourhood: str, driver:webdriver = CHROME_DRIVER):
    
    try:
        # Navigate to the URL
        url = f"https://condos.ca/{neighbourhood}?mode=Sale"
        driver.get(url)
        
        # Wait for 10 seconds
        time.sleep(10)
        
        # Extract the HTML of the entire webpage
        html_content = driver.page_source
        return extract_listings_found(html_content)
        
    finally:
        # Close the browser
        driver.quit()
